version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "postgres:9.6.3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--timeout=15", "--username=postgres", "--dbname=phoenix_aptlist_dev"]
      interval: 30s
      timeout: 30s
      retries: 3
